name: Build
run-name: Checking the build after the Push/PR by ${{ github.actor }}
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"

      - name: Build with Gradle
        run: ./gradlew build

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2.16.1
        if: always()
        with:
          files: |
            build/test-results/test/TEST-*.xml

      - name: Publish Test Summary
        uses: test-summary/action@v2.3
        if: always()
        with:
          paths: "build/test-results/test/TEST-*.xml"

      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          jacoco-csv-file: build/jacocoReportDir/test/jacocoTestReport.csv

      - name: Update Jacoco Badge
        uses: test-room-7/action-update-file@v1
        with:
          file-path: .github/badges/jacoco.svg
          commit-msg: Update Jacoco Badge
          github-token: ${{ secrets.GITHUB_TOKEN }}

    permissions:
      checks: write
      pull-requests: write