name: Generate JaCoCo Badge
run-name: Updating JaCoCo Badge after ${{ github.actor }}
on: [push]
jobs:
  Test-PR:
    runs-on: ubuntu-latest
    steps:
    - name: Generate JaCoCo Badge
      uses: cicirello/jacoco-badge-generator@v2
      with:
        generate-branches-badge: true
        jacoco-csv-file: build/customJacocoReportDir/test/jacocoTestReport.csv

    - name: Update Jacoco Badge
      uses: test-room-7/action-update-file@v1
      with:
        file-path: .github/badges/jacoco.svg
        commit-msg:  Update Jacoco Badge
        github-token: ${{ secrets.GITHUB_TOKEN }}